### PR TITLE
MGDCTRS-1214 Fix K8s resource requests and limits for infrastructure components (Fleetshard-Sync, Camel Operator, Debezium Operator, Camel-K, Strimzi)

### PR DESCRIPTION
**Pull request by rk3rn3r**
closes https://issues.redhat.com/browse/MGDCTRS-1214

### CODE REVIEW

**Comment by rk3rn3r** [comment]
@lburgazzoli  @rinaldodev mind checking if those changes make sense and are correctly integrated in our release pipeline?
Is the integration into cos-manifests automated or do I have to make changes there as well to get those changes into stage/production?

**Comment by rk3rn3r** [comment]
Are changes in `./etc/` not triggering any tests?

**Comment by rinaldodev** [comment]
@rk3rn3r the kubernetes.yml files inside /etc files are actually copied from the ones inside the specific projects, like this one: https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard/blob/main/cos-fleetshard-operator-camel/pom.xml#L180-L189

So it needs to be changed there.

Camel K and Strimzi looks good to me.

**Comment by rk3rn3r** [comment]
Thx for the clarification. But I feel like people don't know that. They highly diverge for example in the case of Camel Operator's kubernetes.yml

**Comment by rk3rn3r** [comment]
@rinaldodev thx! I've updated the poms accordingly.

**Comment by rinaldodev** [comment]
@rk3rn3r you can try to build with `./mvnw clean install -DskipTests` just to see if the files are all correctly generated.

**Pull request merged**
